apiVersion: v1
kind: Namespace
metadata:
  name: todo-app ##Replace this with the name of you namespace.
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-kube
  namespace: todo-app ##Replace this with the name of you namespace.
  labels:
    app: frontend-kube
spec:
  containers:
    - name: frontend-kube
      image: daramirezs/frontend-kube:1.0
      ports:
        - containerPort: 8040
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-kube-service
  namespace: todo-app ##Replace this with the name of you namespace.
spec:
  type: NodePort
  selector:
    app: nginx-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8040
      nodePort: 30000
